# wrangler.toml  — Workers (NOT Pages)

name = "popcorn-ceiling-removal-worker"
main = ".open-next/worker.js"

compatibility_date = "2024-11-08"
compatibility_flags = ["nodejs_compat"]

# get a workers.dev URL (good for testing)
workers_dev = true

[assets]
# let the Worker serve static files via a binding (so SSG routes work)
directory = ".open-next/assets"
binding = "ASSETS"
