# wrangler.toml
name = "popcorn-ceiling-removal-calgary3"   # <-- EXACT Pages project name
pages_build_output_dir = ".open-next"

compatibility_date = "2024-11-08"
compatibility_flags = ["nodejs_compat"]
